### ISSUE TITLE
Creating new project does not work

### ISSUE THREAD

**Issue by sebastianbergmann** [getparthenon/monorepo#40] opened 2023-09-17 09:52 UTC
### Parthenon version(s) affected

parthenon/skeleton 2.1.2

### Description

Following the instructions at https://github.com/getparthenon/skeleton?tab=readme-ov-file#get-started to create a new project, I run into an issue that Composer cannot resolve an installable set of packages.

### How to reproduce

```
$ composer create-project parthenon/skeleton new-application
Creating a "parthenon/skeleton" project at "./new-application"
Installing parthenon/skeleton (v2.1.2)
  - Downloading parthenon/skeleton (v2.1.2)
  - Installing parthenon/skeleton (v2.1.2): Extracting archive
Created project in /tmp/new-application
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires parthenon/parthenon dev-main -> satisfiable by parthenon/parthenon[dev-main].
    - parthenon/parthenon dev-main requires parthenon/obol ^0.2 -> found parthenon/obol[v0.2, v0.2.1, v0.2.2] but it conflicts with your root composer.json require (dev-main).
```

**Comment by theseer** [comment] 2023-09-18 09:29
Even if ignoring the above error and starting the containers, the app crashes the same way:

![image](https://github.com/getparthenon/monorepo/assets/111333/62842e13-ef7d-4b32-9fa8-9a017cabd04f)

**Comment by mazzarito** [comment] 2023-11-28 23:57
+1

**Comment by mazzarito** [comment] 2023-11-28 23:59
Fixed by modifying the composer.json file and changing the parthenon/obol version to * instead of dev-main

**Comment by that-guy-iain** [comment] 2024-04-23 15:27
Wow. I've only just seen this. I have no idea why I missed it. All I can do is say sorry.

**Comment by that-guy-iain** [comment] 2024-04-23 15:30
Just confirmed I fixed this. Someone emailed me and pointed it out. I'll look into my email settings to see why I didn't spot the github notification because this is embarrassing and I don't want it happening again.

**Closed** 2024-04-23 15:32 UTC
